version: 2.1

orbs:
  silta: silta/silta@dev:master

executors:
  silta-latest:
    docker:
      - image: wunderio/silta-circleci:latest

commands:
  set-up-socks-proxy:
    parameters:
      private-key:
        type: string
        default: ''
      public-key:
        type: string
        default: ''
      host:
        type: string
        default: ''
    steps:
      - run:
          name: Add SSH private-key
          command: |
            echo -e "$TUNNEL_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
      - run:
          name: Open up a tunnel
          command: |
            ssh -o StrictHostKeyChecking=accept-new -D 1337 -C -N -q -f "$TUNNEL_USER_HOST"
            #echo "export HTTPS_PROXY=socks5://localhost:1337" >> "$BASH_ENV"
            echo "alias kubectl=\"HTTPS_PROXY=socks5://localhost:1337 kubectl\"" >> "$BASH_ENV"
            echo "alias helm=\"HTTPS_PROXY=socks5://localhost:1337 helm\"" >> "$BASH_ENV"

workflows:
  version: 2
  commit:
    jobs:
      - silta/drupal-validate:
          name: validate
          post-validation:
            - run:
                name: Helm unit tests
                command: helm unittest ./charts/drupal --helm3

      - silta/drupal-build-deploy: &build-deploy
          name: build-deploy

          # Use the latest orb version.
          executor: silta-latest

          # Use a local chart during development.
          chart_name: "./charts/drupal"
          chart_repository: ""
          silta_config: silta/silta.yml
          codebase-build:
            - silta/drupal-composer-install
            - silta/npm-install-build
            - set-up-socks-proxy
          pre-release:
            - run:
                name: Build local helm chart
                command: |
                  helm repo add elastic https://helm.elastic.co
                  helm repo add codecentric https://codecentric.github.io/helm-charts
                  helm dependency build ./charts/drupal
            - run:
                name: Dry-run helm install
                command: helm install --dry-run --generate-name ./charts/drupal
          context: silta_small
          filters:
            branches:
              ignore: production

      - silta/drupal-build-deploy:
          # Extend the build-deploy configuration for the production environment.
          <<: *build-deploy
          name: build-deploy-prod
          silta_config: silta/silta.yml,silta/silta-prod.yml
          context: silta_finland
          filters:
            branches:
              only: production
